/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DefectDetailResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ActionPlanDefectsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class ActionPlanDefectsResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("creation")
  private String creation = null;

  @SerializedName("expiration")
  private String expiration = null;

  @SerializedName("createdBy")
  private String createdBy = null;

  @SerializedName("assignedTo")
  private String assignedTo = null;

  @SerializedName("progress")
  private Double progress = null;

  @SerializedName("estimate")
  private String estimate = null;

  @SerializedName("pendingEffort")
  private String pendingEffort = null;

  @SerializedName("purged")
  private Boolean purged = null;

  @SerializedName("allDefects")
  private List<DefectDetailResponse> allDefects = null;

  public ActionPlanDefectsResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Action plan name
   * @return name
  **/
  @ApiModelProperty(example = "ActionPlan1", value = "Action plan name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ActionPlanDefectsResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Action plan Description
   * @return description
  **/
  @ApiModelProperty(example = "Action Plan for security defects", value = "Action plan Description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public ActionPlanDefectsResponse creation(String creation) {
    this.creation = creation;
    return this;
  }

   /**
   * Creation time
   * @return creation
  **/
  @ApiModelProperty(example = "2019-10-31T14:50:05.227Z", value = "Creation time")
  public String getCreation() {
    return creation;
  }

  public void setCreation(String creation) {
    this.creation = creation;
  }

  public ActionPlanDefectsResponse expiration(String expiration) {
    this.expiration = expiration;
    return this;
  }

   /**
   * Expiration time
   * @return expiration
  **/
  @ApiModelProperty(example = "2019-11-31T14:50:05.227Z", value = "Expiration time")
  public String getExpiration() {
    return expiration;
  }

  public void setExpiration(String expiration) {
    this.expiration = expiration;
  }

  public ActionPlanDefectsResponse createdBy(String createdBy) {
    this.createdBy = createdBy;
    return this;
  }

   /**
   * User action plan creator
   * @return createdBy
  **/
  @ApiModelProperty(example = "The Boss", value = "User action plan creator")
  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public ActionPlanDefectsResponse assignedTo(String assignedTo) {
    this.assignedTo = assignedTo;
    return this;
  }

   /**
   * User assigned to this action plan
   * @return assignedTo
  **/
  @ApiModelProperty(example = "John Smith", value = "User assigned to this action plan")
  public String getAssignedTo() {
    return assignedTo;
  }

  public void setAssignedTo(String assignedTo) {
    this.assignedTo = assignedTo;
  }

  public ActionPlanDefectsResponse progress(Double progress) {
    this.progress = progress;
    return this;
  }

   /**
   * Action plan progress
   * @return progress
  **/
  @ApiModelProperty(example = "32.5", value = "Action plan progress")
  public Double getProgress() {
    return progress;
  }

  public void setProgress(Double progress) {
    this.progress = progress;
  }

  public ActionPlanDefectsResponse estimate(String estimate) {
    this.estimate = estimate;
    return this;
  }

   /**
   * Total effort estimated time
   * @return estimate
  **/
  @ApiModelProperty(example = "1h 56m", value = "Total effort estimated time")
  public String getEstimate() {
    return estimate;
  }

  public void setEstimate(String estimate) {
    this.estimate = estimate;
  }

  public ActionPlanDefectsResponse pendingEffort(String pendingEffort) {
    this.pendingEffort = pendingEffort;
    return this;
  }

   /**
   * Pending effort estimated time
   * @return pendingEffort
  **/
  @ApiModelProperty(example = "30m", value = "Pending effort estimated time")
  public String getPendingEffort() {
    return pendingEffort;
  }

  public void setPendingEffort(String pendingEffort) {
    this.pendingEffort = pendingEffort;
  }

  public ActionPlanDefectsResponse purged(Boolean purged) {
    this.purged = purged;
    return this;
  }

   /**
   * Indicates if the action plan is purged
   * @return purged
  **/
  @ApiModelProperty(example = "false", value = "Indicates if the action plan is purged")
  public Boolean isPurged() {
    return purged;
  }

  public void setPurged(Boolean purged) {
    this.purged = purged;
  }

  public ActionPlanDefectsResponse allDefects(List<DefectDetailResponse> allDefects) {
    this.allDefects = allDefects;
    return this;
  }

  public ActionPlanDefectsResponse addAllDefectsItem(DefectDetailResponse allDefectsItem) {
    if (this.allDefects == null) {
      this.allDefects = new ArrayList<DefectDetailResponse>();
    }
    this.allDefects.add(allDefectsItem);
    return this;
  }

   /**
   * List of action plan defects
   * @return allDefects
  **/
  @ApiModelProperty(value = "List of action plan defects")
  public List<DefectDetailResponse> getAllDefects() {
    return allDefects;
  }

  public void setAllDefects(List<DefectDetailResponse> allDefects) {
    this.allDefects = allDefects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ActionPlanDefectsResponse actionPlanDefectsResponse = (ActionPlanDefectsResponse) o;
    return Objects.equals(this.name, actionPlanDefectsResponse.name) &&
        Objects.equals(this.description, actionPlanDefectsResponse.description) &&
        Objects.equals(this.creation, actionPlanDefectsResponse.creation) &&
        Objects.equals(this.expiration, actionPlanDefectsResponse.expiration) &&
        Objects.equals(this.createdBy, actionPlanDefectsResponse.createdBy) &&
        Objects.equals(this.assignedTo, actionPlanDefectsResponse.assignedTo) &&
        Objects.equals(this.progress, actionPlanDefectsResponse.progress) &&
        Objects.equals(this.estimate, actionPlanDefectsResponse.estimate) &&
        Objects.equals(this.pendingEffort, actionPlanDefectsResponse.pendingEffort) &&
        Objects.equals(this.purged, actionPlanDefectsResponse.purged) &&
        Objects.equals(this.allDefects, actionPlanDefectsResponse.allDefects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, creation, expiration, createdBy, assignedTo, progress, estimate, pendingEffort, purged, allDefects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ActionPlanDefectsResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    creation: ").append(toIndentedString(creation)).append("\n");
    sb.append("    expiration: ").append(toIndentedString(expiration)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    assignedTo: ").append(toIndentedString(assignedTo)).append("\n");
    sb.append("    progress: ").append(toIndentedString(progress)).append("\n");
    sb.append("    estimate: ").append(toIndentedString(estimate)).append("\n");
    sb.append("    pendingEffort: ").append(toIndentedString(pendingEffort)).append("\n");
    sb.append("    purged: ").append(toIndentedString(purged)).append("\n");
    sb.append("    allDefects: ").append(toIndentedString(allDefects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

