/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FileData;
import io.swagger.client.model.MetadataArchitectureData;
import io.swagger.client.model.MetadataInsightsData;
import io.swagger.client.model.MetricValueData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * AnalysisFilesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class AnalysisFilesResponse {
  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("auditName")
  private String auditName = null;

  /**
   * Application business value
   */
  @JsonAdapter(ApplicationBusinessValueEnum.Adapter.class)
  public enum ApplicationBusinessValueEnum {
    VERY_LOW("VERY LOW"),
    
    LOW("LOW"),
    
    MEDIUM("MEDIUM"),
    
    HIGH("HIGH"),
    
    CRITICAL("CRITICAL");

    private String value;

    ApplicationBusinessValueEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ApplicationBusinessValueEnum fromValue(String text) {
      for (ApplicationBusinessValueEnum b : ApplicationBusinessValueEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ApplicationBusinessValueEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ApplicationBusinessValueEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ApplicationBusinessValueEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ApplicationBusinessValueEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("applicationBusinessValue")
  private ApplicationBusinessValueEnum applicationBusinessValue = null;

  @SerializedName("applicationProvider")
  private String applicationProvider = null;

  @SerializedName("applicationPortfolios")
  private Map<String, String> applicationPortfolios = null;

  @SerializedName("label")
  private String label = null;

  @SerializedName("date")
  private String date = null;

  @SerializedName("modelId")
  private Long modelId = null;

  @SerializedName("encoding")
  private String encoding = null;

  @SerializedName("analysisCode")
  private String analysisCode = null;

  @SerializedName("analysisURL")
  private String analysisURL = null;

  @SerializedName("auditResultURL")
  private String auditResultURL = null;

  /**
   * Analysis business value
   */
  @JsonAdapter(AnalysisBusinessValueEnum.Adapter.class)
  public enum AnalysisBusinessValueEnum {
    VERY_LOW("VERY LOW"),
    
    LOW("LOW"),
    
    MEDIUM("MEDIUM"),
    
    HIGH("HIGH"),
    
    CRITICAL("CRITICAL");

    private String value;

    AnalysisBusinessValueEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisBusinessValueEnum fromValue(String text) {
      for (AnalysisBusinessValueEnum b : AnalysisBusinessValueEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AnalysisBusinessValueEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisBusinessValueEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisBusinessValueEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AnalysisBusinessValueEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("analysisBusinessValue")
  private AnalysisBusinessValueEnum analysisBusinessValue = null;

  @SerializedName("analysisProvider")
  private String analysisProvider = null;

  @SerializedName("analysisPortfolios")
  private Map<String, String> analysisPortfolios = null;

  /**
   * Analysis status
   */
  @JsonAdapter(AnalysisStatusEnum.Adapter.class)
  public enum AnalysisStatusEnum {
    EXECUTING("EXECUTING"),
    
    FINISHED("FINISHED"),
    
    FINISHED_WITH_ERROR("FINISHED_WITH_ERROR");

    private String value;

    AnalysisStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AnalysisStatusEnum fromValue(String text) {
      for (AnalysisStatusEnum b : AnalysisStatusEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<AnalysisStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AnalysisStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AnalysisStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return AnalysisStatusEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("analysisStatus")
  private AnalysisStatusEnum analysisStatus = null;

  @SerializedName("languages")
  private List<MetricValueData> languages = null;

  @SerializedName("architecture")
  private MetadataArchitectureData architecture = null;

  @SerializedName("insightsData")
  private MetadataInsightsData insightsData = null;

  @SerializedName("files_count")
  private Integer filesCount = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("files")
  private List<FileData> files = null;

  @SerializedName("quality_model")
  private String qualityModel = null;

  @SerializedName("ordered_by")
  private String orderedBy = null;

  @SerializedName("Risk index")
  private MetricValueData riskIndex = null;

  @SerializedName("Quality indicator")
  private MetricValueData qualityIndicator = null;

  @SerializedName("Effort to target")
  private MetricValueData effortToTarget = null;

  @SerializedName("Main metrics")
  private List<MetricValueData> mainMetrics = null;

  @SerializedName("Security")
  private Map<String, Object> security = null;

  public AnalysisFilesResponse name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Application name
   * @return name
  **/
  @ApiModelProperty(example = "android", value = "Application name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public AnalysisFilesResponse description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Application description
   * @return description
  **/
  @ApiModelProperty(example = "GitHub Android App", value = "Application description")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public AnalysisFilesResponse auditName(String auditName) {
    this.auditName = auditName;
    return this;
  }

   /**
   * Application audit name
   * @return auditName
  **/
  @ApiModelProperty(example = "Kiuwan default audit", value = "Application audit name")
  public String getAuditName() {
    return auditName;
  }

  public void setAuditName(String auditName) {
    this.auditName = auditName;
  }

  public AnalysisFilesResponse applicationBusinessValue(ApplicationBusinessValueEnum applicationBusinessValue) {
    this.applicationBusinessValue = applicationBusinessValue;
    return this;
  }

   /**
   * Application business value
   * @return applicationBusinessValue
  **/
  @ApiModelProperty(example = "CRITICAL", value = "Application business value")
  public ApplicationBusinessValueEnum getApplicationBusinessValue() {
    return applicationBusinessValue;
  }

  public void setApplicationBusinessValue(ApplicationBusinessValueEnum applicationBusinessValue) {
    this.applicationBusinessValue = applicationBusinessValue;
  }

  public AnalysisFilesResponse applicationProvider(String applicationProvider) {
    this.applicationProvider = applicationProvider;
    return this;
  }

   /**
   * Application provider
   * @return applicationProvider
  **/
  @ApiModelProperty(example = "Lab", value = "Application provider")
  public String getApplicationProvider() {
    return applicationProvider;
  }

  public void setApplicationProvider(String applicationProvider) {
    this.applicationProvider = applicationProvider;
  }

  public AnalysisFilesResponse applicationPortfolios(Map<String, String> applicationPortfolios) {
    this.applicationPortfolios = applicationPortfolios;
    return this;
  }

  public AnalysisFilesResponse putApplicationPortfoliosItem(String key, String applicationPortfoliosItem) {
    if (this.applicationPortfolios == null) {
      this.applicationPortfolios = new HashMap<String, String>();
    }
    this.applicationPortfolios.put(key, applicationPortfoliosItem);
    return this;
  }

   /**
   * Map of application portfolios
   * @return applicationPortfolios
  **/
  @ApiModelProperty(example = "\"{ 'country': 'spain' }\"", value = "Map of application portfolios")
  public Map<String, String> getApplicationPortfolios() {
    return applicationPortfolios;
  }

  public void setApplicationPortfolios(Map<String, String> applicationPortfolios) {
    this.applicationPortfolios = applicationPortfolios;
  }

  public AnalysisFilesResponse label(String label) {
    this.label = label;
    return this;
  }

   /**
   * Analysis label
   * @return label
  **/
  @ApiModelProperty(example = "14.10.2019_1", value = "Analysis label")
  public String getLabel() {
    return label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public AnalysisFilesResponse date(String date) {
    this.date = date;
    return this;
  }

   /**
   * Analysis creation date
   * @return date
  **/
  @ApiModelProperty(example = "2019-10-14T15:15:15Z", value = "Analysis creation date")
  public String getDate() {
    return date;
  }

  public void setDate(String date) {
    this.date = date;
  }

  public AnalysisFilesResponse modelId(Long modelId) {
    this.modelId = modelId;
    return this;
  }

   /**
   * Analysis model identifier
   * @return modelId
  **/
  @ApiModelProperty(example = "6252", value = "Analysis model identifier")
  public Long getModelId() {
    return modelId;
  }

  public void setModelId(Long modelId) {
    this.modelId = modelId;
  }

  public AnalysisFilesResponse encoding(String encoding) {
    this.encoding = encoding;
    return this;
  }

   /**
   * Analysis encoding
   * @return encoding
  **/
  @ApiModelProperty(example = "UTF-8", value = "Analysis encoding")
  public String getEncoding() {
    return encoding;
  }

  public void setEncoding(String encoding) {
    this.encoding = encoding;
  }

  public AnalysisFilesResponse analysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
    return this;
  }

   /**
   * Analysis code
   * @return analysisCode
  **/
  @ApiModelProperty(example = "A-ZBA-234820349", value = "Analysis code")
  public String getAnalysisCode() {
    return analysisCode;
  }

  public void setAnalysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
  }

  public AnalysisFilesResponse analysisURL(String analysisURL) {
    this.analysisURL = analysisURL;
    return this;
  }

   /**
   * Kiuwan link to view the analysis detail
   * @return analysisURL
  **/
  @ApiModelProperty(example = "https://www.kiuwan.com/saas/web/dashboard/dashboard#$pe=application$sei=2401$mi=dashboard$ac=A-ZBA-234820349", value = "Kiuwan link to view the analysis detail")
  public String getAnalysisURL() {
    return analysisURL;
  }

  public void setAnalysisURL(String analysisURL) {
    this.analysisURL = analysisURL;
  }

  public AnalysisFilesResponse auditResultURL(String auditResultURL) {
    this.auditResultURL = auditResultURL;
    return this;
  }

   /**
   * Kiuwan link to view the audit result of the analisys
   * @return auditResultURL
  **/
  @ApiModelProperty(value = "Kiuwan link to view the audit result of the analisys")
  public String getAuditResultURL() {
    return auditResultURL;
  }

  public void setAuditResultURL(String auditResultURL) {
    this.auditResultURL = auditResultURL;
  }

  public AnalysisFilesResponse analysisBusinessValue(AnalysisBusinessValueEnum analysisBusinessValue) {
    this.analysisBusinessValue = analysisBusinessValue;
    return this;
  }

   /**
   * Analysis business value
   * @return analysisBusinessValue
  **/
  @ApiModelProperty(example = "CRITICAL", value = "Analysis business value")
  public AnalysisBusinessValueEnum getAnalysisBusinessValue() {
    return analysisBusinessValue;
  }

  public void setAnalysisBusinessValue(AnalysisBusinessValueEnum analysisBusinessValue) {
    this.analysisBusinessValue = analysisBusinessValue;
  }

  public AnalysisFilesResponse analysisProvider(String analysisProvider) {
    this.analysisProvider = analysisProvider;
    return this;
  }

   /**
   * Analysis provider
   * @return analysisProvider
  **/
  @ApiModelProperty(example = "Lab", value = "Analysis provider")
  public String getAnalysisProvider() {
    return analysisProvider;
  }

  public void setAnalysisProvider(String analysisProvider) {
    this.analysisProvider = analysisProvider;
  }

  public AnalysisFilesResponse analysisPortfolios(Map<String, String> analysisPortfolios) {
    this.analysisPortfolios = analysisPortfolios;
    return this;
  }

  public AnalysisFilesResponse putAnalysisPortfoliosItem(String key, String analysisPortfoliosItem) {
    if (this.analysisPortfolios == null) {
      this.analysisPortfolios = new HashMap<String, String>();
    }
    this.analysisPortfolios.put(key, analysisPortfoliosItem);
    return this;
  }

   /**
   * Map of analysis portfolios
   * @return analysisPortfolios
  **/
  @ApiModelProperty(example = "\"{ 'country': 'spain' }\"", value = "Map of analysis portfolios")
  public Map<String, String> getAnalysisPortfolios() {
    return analysisPortfolios;
  }

  public void setAnalysisPortfolios(Map<String, String> analysisPortfolios) {
    this.analysisPortfolios = analysisPortfolios;
  }

  public AnalysisFilesResponse analysisStatus(AnalysisStatusEnum analysisStatus) {
    this.analysisStatus = analysisStatus;
    return this;
  }

   /**
   * Analysis status
   * @return analysisStatus
  **/
  @ApiModelProperty(example = "FINISHED", value = "Analysis status")
  public AnalysisStatusEnum getAnalysisStatus() {
    return analysisStatus;
  }

  public void setAnalysisStatus(AnalysisStatusEnum analysisStatus) {
    this.analysisStatus = analysisStatus;
  }

  public AnalysisFilesResponse languages(List<MetricValueData> languages) {
    this.languages = languages;
    return this;
  }

  public AnalysisFilesResponse addLanguagesItem(MetricValueData languagesItem) {
    if (this.languages == null) {
      this.languages = new ArrayList<MetricValueData>();
    }
    this.languages.add(languagesItem);
    return this;
  }

   /**
   * Languages metric list
   * @return languages
  **/
  @ApiModelProperty(value = "Languages metric list")
  public List<MetricValueData> getLanguages() {
    return languages;
  }

  public void setLanguages(List<MetricValueData> languages) {
    this.languages = languages;
  }

  public AnalysisFilesResponse architecture(MetadataArchitectureData architecture) {
    this.architecture = architecture;
    return this;
  }

   /**
   * Architecture detail
   * @return architecture
  **/
  @ApiModelProperty(value = "Architecture detail")
  public MetadataArchitectureData getArchitecture() {
    return architecture;
  }

  public void setArchitecture(MetadataArchitectureData architecture) {
    this.architecture = architecture;
  }

  public AnalysisFilesResponse insightsData(MetadataInsightsData insightsData) {
    this.insightsData = insightsData;
    return this;
  }

   /**
   * Insights metadata
   * @return insightsData
  **/
  @ApiModelProperty(value = "Insights metadata")
  public MetadataInsightsData getInsightsData() {
    return insightsData;
  }

  public void setInsightsData(MetadataInsightsData insightsData) {
    this.insightsData = insightsData;
  }

  public AnalysisFilesResponse filesCount(Integer filesCount) {
    this.filesCount = filesCount;
    return this;
  }

   /**
   * Number of files
   * @return filesCount
  **/
  @ApiModelProperty(example = "124", value = "Number of files")
  public Integer getFilesCount() {
    return filesCount;
  }

  public void setFilesCount(Integer filesCount) {
    this.filesCount = filesCount;
  }

  public AnalysisFilesResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of files in this response
   * @return count
  **/
  @ApiModelProperty(example = "100", value = "Number of files in this response")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public AnalysisFilesResponse page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number
   * @return page
  **/
  @ApiModelProperty(example = "1", value = "Page number")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public AnalysisFilesResponse files(List<FileData> files) {
    this.files = files;
    return this;
  }

  public AnalysisFilesResponse addFilesItem(FileData filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<FileData>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Files list
   * @return files
  **/
  @ApiModelProperty(value = "Files list")
  public List<FileData> getFiles() {
    return files;
  }

  public void setFiles(List<FileData> files) {
    this.files = files;
  }

  public AnalysisFilesResponse qualityModel(String qualityModel) {
    this.qualityModel = qualityModel;
    return this;
  }

   /**
   * Application quality model name
   * @return qualityModel
  **/
  @ApiModelProperty(example = "CQM", value = "Application quality model name")
  public String getQualityModel() {
    return qualityModel;
  }

  public void setQualityModel(String qualityModel) {
    this.qualityModel = qualityModel;
  }

  public AnalysisFilesResponse orderedBy(String orderedBy) {
    this.orderedBy = orderedBy;
    return this;
  }

   /**
   * Analysis user invoker
   * @return orderedBy
  **/
  @ApiModelProperty(example = "github software", value = "Analysis user invoker")
  public String getOrderedBy() {
    return orderedBy;
  }

  public void setOrderedBy(String orderedBy) {
    this.orderedBy = orderedBy;
  }

  public AnalysisFilesResponse riskIndex(MetricValueData riskIndex) {
    this.riskIndex = riskIndex;
    return this;
  }

   /**
   * Risk index metric
   * @return riskIndex
  **/
  @ApiModelProperty(value = "Risk index metric")
  public MetricValueData getRiskIndex() {
    return riskIndex;
  }

  public void setRiskIndex(MetricValueData riskIndex) {
    this.riskIndex = riskIndex;
  }

  public AnalysisFilesResponse qualityIndicator(MetricValueData qualityIndicator) {
    this.qualityIndicator = qualityIndicator;
    return this;
  }

   /**
   * Quality indicator metric
   * @return qualityIndicator
  **/
  @ApiModelProperty(value = "Quality indicator metric")
  public MetricValueData getQualityIndicator() {
    return qualityIndicator;
  }

  public void setQualityIndicator(MetricValueData qualityIndicator) {
    this.qualityIndicator = qualityIndicator;
  }

  public AnalysisFilesResponse effortToTarget(MetricValueData effortToTarget) {
    this.effortToTarget = effortToTarget;
    return this;
  }

   /**
   * Effort to target metric
   * @return effortToTarget
  **/
  @ApiModelProperty(value = "Effort to target metric")
  public MetricValueData getEffortToTarget() {
    return effortToTarget;
  }

  public void setEffortToTarget(MetricValueData effortToTarget) {
    this.effortToTarget = effortToTarget;
  }

  public AnalysisFilesResponse mainMetrics(List<MetricValueData> mainMetrics) {
    this.mainMetrics = mainMetrics;
    return this;
  }

  public AnalysisFilesResponse addMainMetricsItem(MetricValueData mainMetricsItem) {
    if (this.mainMetrics == null) {
      this.mainMetrics = new ArrayList<MetricValueData>();
    }
    this.mainMetrics.add(mainMetricsItem);
    return this;
  }

   /**
   * Main metrics list
   * @return mainMetrics
  **/
  @ApiModelProperty(value = "Main metrics list")
  public List<MetricValueData> getMainMetrics() {
    return mainMetrics;
  }

  public void setMainMetrics(List<MetricValueData> mainMetrics) {
    this.mainMetrics = mainMetrics;
  }

   /**
   * Map of security metrics
   * @return security
  **/
  @ApiModelProperty(example = "\"{ 'Rating': 1, {'3Stars':104.6,'5Stars':255.9,'2Stars':64.89,'4Stars':247.4}\"", value = "Map of security metrics")
  public Map<String, Object> getSecurity() {
    return security;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnalysisFilesResponse analysisFilesResponse = (AnalysisFilesResponse) o;
    return Objects.equals(this.name, analysisFilesResponse.name) &&
        Objects.equals(this.description, analysisFilesResponse.description) &&
        Objects.equals(this.auditName, analysisFilesResponse.auditName) &&
        Objects.equals(this.applicationBusinessValue, analysisFilesResponse.applicationBusinessValue) &&
        Objects.equals(this.applicationProvider, analysisFilesResponse.applicationProvider) &&
        Objects.equals(this.applicationPortfolios, analysisFilesResponse.applicationPortfolios) &&
        Objects.equals(this.label, analysisFilesResponse.label) &&
        Objects.equals(this.date, analysisFilesResponse.date) &&
        Objects.equals(this.modelId, analysisFilesResponse.modelId) &&
        Objects.equals(this.encoding, analysisFilesResponse.encoding) &&
        Objects.equals(this.analysisCode, analysisFilesResponse.analysisCode) &&
        Objects.equals(this.analysisURL, analysisFilesResponse.analysisURL) &&
        Objects.equals(this.auditResultURL, analysisFilesResponse.auditResultURL) &&
        Objects.equals(this.analysisBusinessValue, analysisFilesResponse.analysisBusinessValue) &&
        Objects.equals(this.analysisProvider, analysisFilesResponse.analysisProvider) &&
        Objects.equals(this.analysisPortfolios, analysisFilesResponse.analysisPortfolios) &&
        Objects.equals(this.analysisStatus, analysisFilesResponse.analysisStatus) &&
        Objects.equals(this.languages, analysisFilesResponse.languages) &&
        Objects.equals(this.architecture, analysisFilesResponse.architecture) &&
        Objects.equals(this.insightsData, analysisFilesResponse.insightsData) &&
        Objects.equals(this.filesCount, analysisFilesResponse.filesCount) &&
        Objects.equals(this.count, analysisFilesResponse.count) &&
        Objects.equals(this.page, analysisFilesResponse.page) &&
        Objects.equals(this.files, analysisFilesResponse.files) &&
        Objects.equals(this.qualityModel, analysisFilesResponse.qualityModel) &&
        Objects.equals(this.orderedBy, analysisFilesResponse.orderedBy) &&
        Objects.equals(this.riskIndex, analysisFilesResponse.riskIndex) &&
        Objects.equals(this.qualityIndicator, analysisFilesResponse.qualityIndicator) &&
        Objects.equals(this.effortToTarget, analysisFilesResponse.effortToTarget) &&
        Objects.equals(this.mainMetrics, analysisFilesResponse.mainMetrics) &&
        Objects.equals(this.security, analysisFilesResponse.security);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, auditName, applicationBusinessValue, applicationProvider, applicationPortfolios, label, date, modelId, encoding, analysisCode, analysisURL, auditResultURL, analysisBusinessValue, analysisProvider, analysisPortfolios, analysisStatus, languages, architecture, insightsData, filesCount, count, page, files, qualityModel, orderedBy, riskIndex, qualityIndicator, effortToTarget, mainMetrics, security);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnalysisFilesResponse {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    auditName: ").append(toIndentedString(auditName)).append("\n");
    sb.append("    applicationBusinessValue: ").append(toIndentedString(applicationBusinessValue)).append("\n");
    sb.append("    applicationProvider: ").append(toIndentedString(applicationProvider)).append("\n");
    sb.append("    applicationPortfolios: ").append(toIndentedString(applicationPortfolios)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    date: ").append(toIndentedString(date)).append("\n");
    sb.append("    modelId: ").append(toIndentedString(modelId)).append("\n");
    sb.append("    encoding: ").append(toIndentedString(encoding)).append("\n");
    sb.append("    analysisCode: ").append(toIndentedString(analysisCode)).append("\n");
    sb.append("    analysisURL: ").append(toIndentedString(analysisURL)).append("\n");
    sb.append("    auditResultURL: ").append(toIndentedString(auditResultURL)).append("\n");
    sb.append("    analysisBusinessValue: ").append(toIndentedString(analysisBusinessValue)).append("\n");
    sb.append("    analysisProvider: ").append(toIndentedString(analysisProvider)).append("\n");
    sb.append("    analysisPortfolios: ").append(toIndentedString(analysisPortfolios)).append("\n");
    sb.append("    analysisStatus: ").append(toIndentedString(analysisStatus)).append("\n");
    sb.append("    languages: ").append(toIndentedString(languages)).append("\n");
    sb.append("    architecture: ").append(toIndentedString(architecture)).append("\n");
    sb.append("    insightsData: ").append(toIndentedString(insightsData)).append("\n");
    sb.append("    filesCount: ").append(toIndentedString(filesCount)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    qualityModel: ").append(toIndentedString(qualityModel)).append("\n");
    sb.append("    orderedBy: ").append(toIndentedString(orderedBy)).append("\n");
    sb.append("    riskIndex: ").append(toIndentedString(riskIndex)).append("\n");
    sb.append("    qualityIndicator: ").append(toIndentedString(qualityIndicator)).append("\n");
    sb.append("    effortToTarget: ").append(toIndentedString(effortToTarget)).append("\n");
    sb.append("    mainMetrics: ").append(toIndentedString(mainMetrics)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

