/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.DefectDetailResponse;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * DefectsKeptInCommonDetailResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class DefectsKeptInCommonDetailResponse {
  @SerializedName("sinceAnalysisCode")
  private String sinceAnalysisCode = null;

  @SerializedName("atAnalysisCode")
  private String atAnalysisCode = null;

  @SerializedName("sinceDate")
  private String sinceDate = null;

  @SerializedName("ruleTags")
  private String ruleTags = null;

  @SerializedName("securityOnly")
  private Boolean securityOnly = null;

  @SerializedName("totalDefects")
  private Long totalDefects = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("defects")
  private List<DefectDetailResponse> defects = null;

  public DefectsKeptInCommonDetailResponse sinceAnalysisCode(String sinceAnalysisCode) {
    this.sinceAnalysisCode = sinceAnalysisCode;
    return this;
  }

   /**
   * Since Analysis Code
   * @return sinceAnalysisCode
  **/
  @ApiModelProperty(example = "A-7e3-16e5b1aad2a", value = "Since Analysis Code")
  public String getSinceAnalysisCode() {
    return sinceAnalysisCode;
  }

  public void setSinceAnalysisCode(String sinceAnalysisCode) {
    this.sinceAnalysisCode = sinceAnalysisCode;
  }

  public DefectsKeptInCommonDetailResponse atAnalysisCode(String atAnalysisCode) {
    this.atAnalysisCode = atAnalysisCode;
    return this;
  }

   /**
   * at analysis code
   * @return atAnalysisCode
  **/
  @ApiModelProperty(example = "A-7e3-16dc9e29131", value = "at analysis code")
  public String getAtAnalysisCode() {
    return atAnalysisCode;
  }

  public void setAtAnalysisCode(String atAnalysisCode) {
    this.atAnalysisCode = atAnalysisCode;
  }

  public DefectsKeptInCommonDetailResponse sinceDate(String sinceDate) {
    this.sinceDate = sinceDate;
    return this;
  }

   /**
   * Since Date
   * @return sinceDate
  **/
  @ApiModelProperty(example = "2020-03-01T12:00:00Z", value = "Since Date")
  public String getSinceDate() {
    return sinceDate;
  }

  public void setSinceDate(String sinceDate) {
    this.sinceDate = sinceDate;
  }

  public DefectsKeptInCommonDetailResponse ruleTags(String ruleTags) {
    this.ruleTags = ruleTags;
    return this;
  }

   /**
   * With rules with tags
   * @return ruleTags
  **/
  @ApiModelProperty(example = "PCI-DSS:6.5.1,cwe99", value = "With rules with tags")
  public String getRuleTags() {
    return ruleTags;
  }

  public void setRuleTags(String ruleTags) {
    this.ruleTags = ruleTags;
  }

  public DefectsKeptInCommonDetailResponse securityOnly(Boolean securityOnly) {
    this.securityOnly = securityOnly;
    return this;
  }

   /**
   * Security Only rules
   * @return securityOnly
  **/
  @ApiModelProperty(example = "true", value = "Security Only rules")
  public Boolean isSecurityOnly() {
    return securityOnly;
  }

  public void setSecurityOnly(Boolean securityOnly) {
    this.securityOnly = securityOnly;
  }

  public DefectsKeptInCommonDetailResponse totalDefects(Long totalDefects) {
    this.totalDefects = totalDefects;
    return this;
  }

   /**
   * Total Defects in Common
   * @return totalDefects
  **/
  @ApiModelProperty(example = "132", value = "Total Defects in Common")
  public Long getTotalDefects() {
    return totalDefects;
  }

  public void setTotalDefects(Long totalDefects) {
    this.totalDefects = totalDefects;
  }

  public DefectsKeptInCommonDetailResponse count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Number of defects in this response
   * @return count
  **/
  @ApiModelProperty(example = "3", value = "Number of defects in this response")
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public DefectsKeptInCommonDetailResponse page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * Page number
   * @return page
  **/
  @ApiModelProperty(example = "1", value = "Page number")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public DefectsKeptInCommonDetailResponse defects(List<DefectDetailResponse> defects) {
    this.defects = defects;
    return this;
  }

  public DefectsKeptInCommonDetailResponse addDefectsItem(DefectDetailResponse defectsItem) {
    if (this.defects == null) {
      this.defects = new ArrayList<DefectDetailResponse>();
    }
    this.defects.add(defectsItem);
    return this;
  }

   /**
   * defects
   * @return defects
  **/
  @ApiModelProperty(value = "defects")
  public List<DefectDetailResponse> getDefects() {
    return defects;
  }

  public void setDefects(List<DefectDetailResponse> defects) {
    this.defects = defects;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DefectsKeptInCommonDetailResponse defectsKeptInCommonDetailResponse = (DefectsKeptInCommonDetailResponse) o;
    return Objects.equals(this.sinceAnalysisCode, defectsKeptInCommonDetailResponse.sinceAnalysisCode) &&
        Objects.equals(this.atAnalysisCode, defectsKeptInCommonDetailResponse.atAnalysisCode) &&
        Objects.equals(this.sinceDate, defectsKeptInCommonDetailResponse.sinceDate) &&
        Objects.equals(this.ruleTags, defectsKeptInCommonDetailResponse.ruleTags) &&
        Objects.equals(this.securityOnly, defectsKeptInCommonDetailResponse.securityOnly) &&
        Objects.equals(this.totalDefects, defectsKeptInCommonDetailResponse.totalDefects) &&
        Objects.equals(this.count, defectsKeptInCommonDetailResponse.count) &&
        Objects.equals(this.page, defectsKeptInCommonDetailResponse.page) &&
        Objects.equals(this.defects, defectsKeptInCommonDetailResponse.defects);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sinceAnalysisCode, atAnalysisCode, sinceDate, ruleTags, securityOnly, totalDefects, count, page, defects);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DefectsKeptInCommonDetailResponse {\n");
    
    sb.append("    sinceAnalysisCode: ").append(toIndentedString(sinceAnalysisCode)).append("\n");
    sb.append("    atAnalysisCode: ").append(toIndentedString(atAnalysisCode)).append("\n");
    sb.append("    sinceDate: ").append(toIndentedString(sinceDate)).append("\n");
    sb.append("    ruleTags: ").append(toIndentedString(ruleTags)).append("\n");
    sb.append("    securityOnly: ").append(toIndentedString(securityOnly)).append("\n");
    sb.append("    totalDefects: ").append(toIndentedString(totalDefects)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    defects: ").append(toIndentedString(defects)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

