/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.ObsolescenceRestData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ListObsolescencesResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class ListObsolescencesResponse {
  @SerializedName("data")
  private List<ObsolescenceRestData> data = null;

  public ListObsolescencesResponse data(List<ObsolescenceRestData> data) {
    this.data = data;
    return this;
  }

  public ListObsolescencesResponse addDataItem(ObsolescenceRestData dataItem) {
    if (this.data == null) {
      this.data = new ArrayList<ObsolescenceRestData>();
    }
    this.data.add(dataItem);
    return this;
  }

   /**
   * Insights components obsolescence detail list
   * @return data
  **/
  @ApiModelProperty(value = "Insights components obsolescence detail list")
  public List<ObsolescenceRestData> getData() {
    return data;
  }

  public void setData(List<ObsolescenceRestData> data) {
    this.data = data;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ListObsolescencesResponse listObsolescencesResponse = (ListObsolescencesResponse) o;
    return Objects.equals(this.data, listObsolescencesResponse.data);
  }

  @Override
  public int hashCode() {
    return Objects.hash(data);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ListObsolescencesResponse {\n");
    
    sb.append("    data: ").append(toIndentedString(data)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

