/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Mapping
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class Mapping {
  /**
   * Mapping type
   */
  @JsonAdapter(MappingTypeEnum.Adapter.class)
  public enum MappingTypeEnum {
    CWE("CWE"),
    
    CVE("CVE"),
    
    OTHER("OTHER"),
    
    TOOL_VENDOR("TOOL_VENDOR");

    private String value;

    MappingTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MappingTypeEnum fromValue(String text) {
      for (MappingTypeEnum b : MappingTypeEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<MappingTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MappingTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MappingTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MappingTypeEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("mappingType")
  private MappingTypeEnum mappingType = null;

  @SerializedName("vendorOtherType")
  private String vendorOtherType = null;

  @SerializedName("value")
  private String value = null;

  @SerializedName("primary")
  private Boolean primary = null;

  public Mapping mappingType(MappingTypeEnum mappingType) {
    this.mappingType = mappingType;
    return this;
  }

   /**
   * Mapping type
   * @return mappingType
  **/
  @ApiModelProperty(example = "CWE", value = "Mapping type")
  public MappingTypeEnum getMappingType() {
    return mappingType;
  }

  public void setMappingType(MappingTypeEnum mappingType) {
    this.mappingType = mappingType;
  }

  public Mapping vendorOtherType(String vendorOtherType) {
    this.vendorOtherType = vendorOtherType;
    return this;
  }

   /**
   * Other type vendor. Required for &#39;OTHER&#39; and &#39;TOOL_VENDOR&#39; mappingType; optional for &#39;CWE&#39; and &#39;CVE&#39;
   * @return vendorOtherType
  **/
  @ApiModelProperty(example = "kiuwan", value = "Other type vendor. Required for 'OTHER' and 'TOOL_VENDOR' mappingType; optional for 'CWE' and 'CVE'")
  public String getVendorOtherType() {
    return vendorOtherType;
  }

  public void setVendorOtherType(String vendorOtherType) {
    this.vendorOtherType = vendorOtherType;
  }

  public Mapping value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Mapping value (CWE id or Kiuwan rule code)
   * @return value
  **/
  @ApiModelProperty(example = "89", value = "Mapping value (CWE id or Kiuwan rule code)")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public Mapping primary(Boolean primary) {
    this.primary = primary;
    return this;
  }

   /**
   * True depending on whether this is the primary for the mappingType
   * @return primary
  **/
  @ApiModelProperty(example = "true", value = "True depending on whether this is the primary for the mappingType")
  public Boolean isPrimary() {
    return primary;
  }

  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Mapping mapping = (Mapping) o;
    return Objects.equals(this.mappingType, mapping.mappingType) &&
        Objects.equals(this.vendorOtherType, mapping.vendorOtherType) &&
        Objects.equals(this.value, mapping.value) &&
        Objects.equals(this.primary, mapping.primary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mappingType, vendorOtherType, value, primary);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Mapping {\n");
    
    sb.append("    mappingType: ").append(toIndentedString(mappingType)).append("\n");
    sb.append("    vendorOtherType: ").append(toIndentedString(vendorOtherType)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    primary: ").append(toIndentedString(primary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

