/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.MetadataInsightsRiskData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * MetadataInsightsData
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class MetadataInsightsData {
  @SerializedName("components")
  private Integer components = null;

  @SerializedName("vulnerabilities")
  private Integer vulnerabilities = null;

  @SerializedName("licenses")
  private Integer licenses = null;

  @SerializedName("duplicates")
  private Integer duplicates = null;

  @SerializedName("risks")
  private List<MetadataInsightsRiskData> risks = null;

  public MetadataInsightsData components(Integer components) {
    this.components = components;
    return this;
  }

   /**
   * Number of components in current analysis
   * @return components
  **/
  @ApiModelProperty(example = "29", value = "Number of components in current analysis")
  public Integer getComponents() {
    return components;
  }

  public void setComponents(Integer components) {
    this.components = components;
  }

  public MetadataInsightsData vulnerabilities(Integer vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
    return this;
  }

   /**
   * Number of vulnerabilities in current analysis
   * @return vulnerabilities
  **/
  @ApiModelProperty(example = "15", value = "Number of vulnerabilities in current analysis")
  public Integer getVulnerabilities() {
    return vulnerabilities;
  }

  public void setVulnerabilities(Integer vulnerabilities) {
    this.vulnerabilities = vulnerabilities;
  }

  public MetadataInsightsData licenses(Integer licenses) {
    this.licenses = licenses;
    return this;
  }

   /**
   * Number of different licenses in current analysis
   * @return licenses
  **/
  @ApiModelProperty(example = "8", value = "Number of different licenses in current analysis")
  public Integer getLicenses() {
    return licenses;
  }

  public void setLicenses(Integer licenses) {
    this.licenses = licenses;
  }

  public MetadataInsightsData duplicates(Integer duplicates) {
    this.duplicates = duplicates;
    return this;
  }

   /**
   * Number of duplicated components in current analysis
   * @return duplicates
  **/
  @ApiModelProperty(example = "8", value = "Number of duplicated components in current analysis")
  public Integer getDuplicates() {
    return duplicates;
  }

  public void setDuplicates(Integer duplicates) {
    this.duplicates = duplicates;
  }

  public MetadataInsightsData risks(List<MetadataInsightsRiskData> risks) {
    this.risks = risks;
    return this;
  }

  public MetadataInsightsData addRisksItem(MetadataInsightsRiskData risksItem) {
    if (this.risks == null) {
      this.risks = new ArrayList<MetadataInsightsRiskData>();
    }
    this.risks.add(risksItem);
    return this;
  }

   /**
   * Risk metadata for current analysis. Risk components by vulnerabilities, by licenses and obsolescence
   * @return risks
  **/
  @ApiModelProperty(value = "Risk metadata for current analysis. Risk components by vulnerabilities, by licenses and obsolescence")
  public List<MetadataInsightsRiskData> getRisks() {
    return risks;
  }

  public void setRisks(List<MetadataInsightsRiskData> risks) {
    this.risks = risks;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetadataInsightsData metadataInsightsData = (MetadataInsightsData) o;
    return Objects.equals(this.components, metadataInsightsData.components) &&
        Objects.equals(this.vulnerabilities, metadataInsightsData.vulnerabilities) &&
        Objects.equals(this.licenses, metadataInsightsData.licenses) &&
        Objects.equals(this.duplicates, metadataInsightsData.duplicates) &&
        Objects.equals(this.risks, metadataInsightsData.risks);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, vulnerabilities, licenses, duplicates, risks);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetadataInsightsData {\n");
    
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    vulnerabilities: ").append(toIndentedString(vulnerabilities)).append("\n");
    sb.append("    licenses: ").append(toIndentedString(licenses)).append("\n");
    sb.append("    duplicates: ").append(toIndentedString(duplicates)).append("\n");
    sb.append("    risks: ").append(toIndentedString(risks)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

