/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.FilterData;
import io.swagger.client.model.NavigationFilterData;
import io.swagger.client.model.PaginationData;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * It is mandatory at least one of the following parameters, application name, analysis code or analysis impact code. If you have already indicated the analysis impact code, the navigation filter is not necessary, in other cases it is. Indicating the pagination filter is necessary in any case.
 */
@ApiModel(description = "It is mandatory at least one of the following parameters, application name, analysis code or analysis impact code. If you have already indicated the analysis impact code, the navigation filter is not necessary, in other cases it is. Indicating the pagination filter is necessary in any case.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2020-05-14T08:41:48.057Z")
public class SearchTargetsImpactRequest {
  @SerializedName("applicationName")
  private String applicationName = null;

  @SerializedName("analysisCode")
  private String analysisCode = null;

  @SerializedName("analysisImpactCode")
  private String analysisImpactCode = null;

  @SerializedName("sourceFilter")
  private FilterData sourceFilter = null;

  @SerializedName("targetFilter")
  private FilterData targetFilter = null;

  @SerializedName("sourceIds")
  private List<Long> sourceIds = null;

  @SerializedName("targetIds")
  private List<Long> targetIds = null;

  @SerializedName("navigationFilter")
  private NavigationFilterData navigationFilter = null;

  @SerializedName("pagination")
  private PaginationData pagination = null;

  public SearchTargetsImpactRequest applicationName(String applicationName) {
    this.applicationName = applicationName;
    return this;
  }

   /**
   * Application name
   * @return applicationName
  **/
  @ApiModelProperty(example = "myApp", value = "Application name")
  public String getApplicationName() {
    return applicationName;
  }

  public void setApplicationName(String applicationName) {
    this.applicationName = applicationName;
  }

  public SearchTargetsImpactRequest analysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
    return this;
  }

   /**
   * Analysis code
   * @return analysisCode
  **/
  @ApiModelProperty(example = "A-7e3-16dc9e29131", value = "Analysis code")
  public String getAnalysisCode() {
    return analysisCode;
  }

  public void setAnalysisCode(String analysisCode) {
    this.analysisCode = analysisCode;
  }

  public SearchTargetsImpactRequest analysisImpactCode(String analysisImpactCode) {
    this.analysisImpactCode = analysisImpactCode;
    return this;
  }

   /**
   * Analysis impact code
   * @return analysisImpactCode
  **/
  @ApiModelProperty(example = "0143dde8-3d81-44ac-ab77-fb5132c0f3b0", value = "Analysis impact code")
  public String getAnalysisImpactCode() {
    return analysisImpactCode;
  }

  public void setAnalysisImpactCode(String analysisImpactCode) {
    this.analysisImpactCode = analysisImpactCode;
  }

  public SearchTargetsImpactRequest sourceFilter(FilterData sourceFilter) {
    this.sourceFilter = sourceFilter;
    return this;
  }

   /**
   * Source filter
   * @return sourceFilter
  **/
  @ApiModelProperty(value = "Source filter")
  public FilterData getSourceFilter() {
    return sourceFilter;
  }

  public void setSourceFilter(FilterData sourceFilter) {
    this.sourceFilter = sourceFilter;
  }

  public SearchTargetsImpactRequest targetFilter(FilterData targetFilter) {
    this.targetFilter = targetFilter;
    return this;
  }

   /**
   * Target filter
   * @return targetFilter
  **/
  @ApiModelProperty(value = "Target filter")
  public FilterData getTargetFilter() {
    return targetFilter;
  }

  public void setTargetFilter(FilterData targetFilter) {
    this.targetFilter = targetFilter;
  }

  public SearchTargetsImpactRequest sourceIds(List<Long> sourceIds) {
    this.sourceIds = sourceIds;
    return this;
  }

  public SearchTargetsImpactRequest addSourceIdsItem(Long sourceIdsItem) {
    if (this.sourceIds == null) {
      this.sourceIds = new ArrayList<Long>();
    }
    this.sourceIds.add(sourceIdsItem);
    return this;
  }

   /**
   * Source identificators
   * @return sourceIds
  **/
  @ApiModelProperty(value = "Source identificators")
  public List<Long> getSourceIds() {
    return sourceIds;
  }

  public void setSourceIds(List<Long> sourceIds) {
    this.sourceIds = sourceIds;
  }

  public SearchTargetsImpactRequest targetIds(List<Long> targetIds) {
    this.targetIds = targetIds;
    return this;
  }

  public SearchTargetsImpactRequest addTargetIdsItem(Long targetIdsItem) {
    if (this.targetIds == null) {
      this.targetIds = new ArrayList<Long>();
    }
    this.targetIds.add(targetIdsItem);
    return this;
  }

   /**
   * Target identificators
   * @return targetIds
  **/
  @ApiModelProperty(value = "Target identificators")
  public List<Long> getTargetIds() {
    return targetIds;
  }

  public void setTargetIds(List<Long> targetIds) {
    this.targetIds = targetIds;
  }

  public SearchTargetsImpactRequest navigationFilter(NavigationFilterData navigationFilter) {
    this.navigationFilter = navigationFilter;
    return this;
  }

   /**
   * Navigation filter
   * @return navigationFilter
  **/
  @ApiModelProperty(value = "Navigation filter")
  public NavigationFilterData getNavigationFilter() {
    return navigationFilter;
  }

  public void setNavigationFilter(NavigationFilterData navigationFilter) {
    this.navigationFilter = navigationFilter;
  }

  public SearchTargetsImpactRequest pagination(PaginationData pagination) {
    this.pagination = pagination;
    return this;
  }

   /**
   * Pagination
   * @return pagination
  **/
  @ApiModelProperty(required = true, value = "Pagination")
  public PaginationData getPagination() {
    return pagination;
  }

  public void setPagination(PaginationData pagination) {
    this.pagination = pagination;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchTargetsImpactRequest searchTargetsImpactRequest = (SearchTargetsImpactRequest) o;
    return Objects.equals(this.applicationName, searchTargetsImpactRequest.applicationName) &&
        Objects.equals(this.analysisCode, searchTargetsImpactRequest.analysisCode) &&
        Objects.equals(this.analysisImpactCode, searchTargetsImpactRequest.analysisImpactCode) &&
        Objects.equals(this.sourceFilter, searchTargetsImpactRequest.sourceFilter) &&
        Objects.equals(this.targetFilter, searchTargetsImpactRequest.targetFilter) &&
        Objects.equals(this.sourceIds, searchTargetsImpactRequest.sourceIds) &&
        Objects.equals(this.targetIds, searchTargetsImpactRequest.targetIds) &&
        Objects.equals(this.navigationFilter, searchTargetsImpactRequest.navigationFilter) &&
        Objects.equals(this.pagination, searchTargetsImpactRequest.pagination);
  }

  @Override
  public int hashCode() {
    return Objects.hash(applicationName, analysisCode, analysisImpactCode, sourceFilter, targetFilter, sourceIds, targetIds, navigationFilter, pagination);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchTargetsImpactRequest {\n");
    
    sb.append("    applicationName: ").append(toIndentedString(applicationName)).append("\n");
    sb.append("    analysisCode: ").append(toIndentedString(analysisCode)).append("\n");
    sb.append("    analysisImpactCode: ").append(toIndentedString(analysisImpactCode)).append("\n");
    sb.append("    sourceFilter: ").append(toIndentedString(sourceFilter)).append("\n");
    sb.append("    targetFilter: ").append(toIndentedString(targetFilter)).append("\n");
    sb.append("    sourceIds: ").append(toIndentedString(sourceIds)).append("\n");
    sb.append("    targetIds: ").append(toIndentedString(targetIds)).append("\n");
    sb.append("    navigationFilter: ").append(toIndentedString(navigationFilter)).append("\n");
    sb.append("    pagination: ").append(toIndentedString(pagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

