/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.AnalysisResponse;
import io.swagger.client.model.AnalysisResultResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DeliveryApi
 */
@Ignore
public class DeliveryApiTest {

    private final DeliveryApi api = new DeliveryApi();

    
    /**
     * Get information of a delivery by code
     *
     * Obtains the information of delivery indicating the code of the delivery.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getDeliveryTest() throws ApiException {
        String code = null;
        AnalysisResultResponse response = api.getDelivery(code);

        // TODO: test validations
    }
    
    /**
     * Get deliveries of an application
     *
     * Obtains the deliveries indicating the name of the application.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listDeliveriesTest() throws ApiException {
        String application = null;
        Integer maxdays = null;
        Integer page = null;
        Integer count = null;
        Boolean auditSuccess = null;
        Boolean filterPurgedAnalyses = null;
        String changeRequestFilter = null;
        List<AnalysisResponse> response = api.listDeliveries(application, maxdays, page, count, auditSuccess, filterPurgedAnalyses, changeRequestFilter);

        // TODO: test validations
    }
    
}
