/*
 * Kiuwan REST API
 * Kiuwan REST API specification
 *
 * OpenAPI spec version: 2.8.2004.3-SNAPSHOT
 * Contact: support@kiuwan.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.RuleDocumentationResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DocumentationApi
 */
@Ignore
public class DocumentationApiTest {

    private final DocumentationApi api = new DocumentationApi();

    
    /**
     * Get rule&#39;s documentation
     *
     * Obtains the documentation of a rule.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getRuleDocTest() throws ApiException {
        String modelId = null;
        String code = null;
        String application = null;
        RuleDocumentationResponse response = api.getRuleDoc(modelId, code, application);

        // TODO: test validations
    }
    
}
